import React from "react";

function FavesPage(props) {
  const items = [
    {
      Name: "Muzil",
      Category: "Color",
      "Top Pick": "checked",
      "Use Case": "Inspiration",
      App: "",
      Review:
        "The stand-out feature is the ability to preview the color scheme on a mock dashboard.\nIt's easy to use color palette generator from the makers of InVision prototyping software.",
      Headline: "",
      Description:
        "Discover color palettes and preview them in a mock user interface.",
      Cost: "",
      Details: "Discover color palettes and preview them on ",
      Website: "https://colors.muz.li/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "2 Colors",
      Category: "Color",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "Quickly browse 2-color combinations.",
      Cost: "Free",
      Details: "2 Color Combinations\n",
      Website: "https://2colors.colorion.co/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "abstrakt",
      Category: "Illustration",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Download our free and premium abstract illustrations for your next landing page, mobile app and presentation.\n",
      Website: "https://www.abstrakt.design/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "absurd design",
      Category: "Illustration",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details: "absurd illustrations that make sense",
      Website: "https://absurd.design/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "Adobe Color",
      Category: "Color",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Create color palettes with the color wheel or image, browse thousands of color combinations from the Adobe Color community.\n",
      Website: "https://color.adobe.com/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "Adobe XD",
      Category: "Prototyping ,Design Tools",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Adobe XD is your UI/UX design solution for website and mobile apps creation. Design, prototype, and share. Try it now.",
      Website: "https://www.adobe.com/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "Airbnb Design",
      Category: "Design Systems",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Building a Visual Language\nBehind the scenes of our new design system\n",
      Website: "https://airbnb.design/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "amritpaldesign",
      Category: "Illustration",
      "Top Pick": "",
      "Use Case": "Inspiration,Downloads",
      App: "",
      Review:
        "Checking out Amrit's work will make you seriously contemplate micro-dosing. Mind-warping 3D illustrations, icons and characters.",
      Headline: "",
      Description: "",
      Cost: "One-Time Fee,Free",
      Details: "Series of iconic rooms illustrated in quarantine. ",
      Website: "https://amritpaldesign.com/3d-rooms-project",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "animockup",
      Category: "Mockups",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Create your free animated product mockup with Animockup. Make videos and animated GIFs for social media, landing pages, Dribbble, and more.",
      Website: "https://animockup.com/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "Apple",
      Category: "Icons",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "With over 2,400 configurable symbols, SF Symbols is designed to integrate seamlessly with San Francisco, the system font for Apple platforms",
      Website: "https://developer.apple.com/sf-symbols/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "archetypeapp",
      Category: "Font",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Looking for a lovely, compatible pair of fonts for your project? Use this tool to find them.\n\n",
      Website: "https://archetypeapp.com/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "Atlassian Design",
      Category: "Design Systems",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Use Atlassian’s end-to-end design language to create straightforward and beautiful experiences.",
      Website: "https://atlassian.design/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "avataaars",
      Category: "Illustration",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details: "Mix & Match Avatars with a Sketch library\n",
      Website: "https://avataaars.com/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "Awwwards ",
      Category: "Inspiration",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Awwwards are the Website Awards that recognize and promote the talent and effort of the best developers, designers and web agencies in the world.\n\n",
      Website: "https://www.awwwards.com/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "barnimages",
      Category: "Stock Photos",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details: "Free high-resolution images for everyone.\n",
      Website: "https://barnimages.com/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "basicons",
      Category: "Icons",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details: "Basic icons for product design & development\n",
      Website: "https://basicons.xyz/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "Behance ",
      Category: "Inspiration",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details: "Showcase and discover the latest work from top designers\n\n\n",
      Website: "https://www.behance.net",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "Bestfolios ",
      Category: "Inspiration",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Bestfolios is the largest curation of best UI/UX designer portfolios, resumes, case studies and design resources.\n",
      Website: "https://www.bestfolios.com/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "bigheads",
      Category: "Illustration",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details: "Randomly Generated Characters for Your Apps & Games\n",
      Website: "https://bigheads.io/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "blackillustrations",
      Category: "Illustration",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details: "The Office Hustle [Medical Pack Included!]",
      Website:
        "https://www.blackillustrations.com/illustrations/the-office-hustle-illustration-pack-official",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "bottts",
      Category: "Illustration",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details: "Mix & Match Robots with a Sketch library\n",
      Website: "https://bottts.com/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "Brand Colors",
      Category: "Color",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "The biggest collection of official brand color codes around. Includes hex colors codes for 500+ brands including Facebook, Twitter, Instagram, and many more.\n",
      Website: "https://brandcolors.net/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "briefbox",
      Category: "Learn Design",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Level up your design & illustration skills working on industry respected practice briefs and short courses :)\n",
      Website: "https://www.briefbox.me/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "Burst By Shopify",
      Category: "Stock Photos",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Browse thousands of beautiful copyright-free images. All our pictures are free to download for personal and commercial use, no attribution required.\n",
      Website: "https://burst.shopify.com/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "carbondesignsystem",
      Category: "Design Systems",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Carbon is IBM’s open source design system for products and digital experiences. With the IBM Design Language as its foundation, the system consists of working code, design tools and resources, human interface guidelines, and a vibrant community of contributors.\n\n",
      Website: "https://www.carbondesignsystem.com/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "casestudy Club",
      Category: "Learn Design",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Learn how people design digital products\nJoin to get curated UX case studies in your inbox every Monday. Trusted by designers from companies like Apple, Google and Spotify. It's 100% free.\n\n",
      Website: "https://www.casestudy.club/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "checklist",
      Category: "Learn Design",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Checklist Design - A collection of the best design practices.\n\n",
      Website: "https://www.checklist.design/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "collectui",
      Category: "Inspiration",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Daily inspiration collected from daily ui archive and beyond. Based on Dribbble shots, hand picked, updating daily.\n",
      Website: "https://collectui.com/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "Color Hunt",
      Category: "Color",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Color Hunt is a free and open platform for color inspiration with thousands of trendy hand-picked color palettes.\n",
      Website: "https://colorhunt.co/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "Color Tool — Material Design",
      Category: "Color",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Create and share color palettes for your UI, and measure the accessibility of any color combination.\n",
      Website: "https://material.io/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "Colorable ",
      Category: "Color",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Contrast is the difference in luminance or color that makes an object (or its representation in an image or display) distinguishable. In visual perception of the real ...\n",
      Website: "https://colorable.jxnblk.com/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "ColorBox",
      Category: "Color",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details: "Colorbox is a color tool to produce color sets.",
      Website: "https://www.colorbox.io/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "colordesigner",
      Category: "Color",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "The main purpose of this tool is to help with building a color palette and generate tints and shades based on it. Just pick a color, and the app does the rest.\n",
      Website: "https://colordesigner.io/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "colorhunt",
      Category: "Color",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Color Hunt is a free and open platform for color inspiration with thousands of trendy hand-picked color palettes\n",
      Website: "https://colorhunt.co/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "colorkit",
      Category: "Color",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "ColorKit blends colors and generates a color's shades and tints.\n",
      Website: "https://colorkit.io/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "colorleap",
      Category: "Color",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details: "Take a leap through time and see the colors of history.\n",
      Website: "https://colorleap.app/home",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "colormind",
      Category: "Color",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Colormind is a color scheme generator that uses deep learning. It can learn color styles from photographs, movies, and popular art.",
      Website: "http://colormind.io/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "colorsinspo",
      Category: "Color",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Thousands of beautiful color palettes you can use it directly by one click.\n",
      Website: "https://colorsinspo.com/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "Colourco",
      Category: "Color",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "colourco.de is an online designer tool, which allows you to easily and intuitively combine colours.\n",
      Website: "https://colourco.de/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "coolicons",
      Category: "Icons",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "coolicons are perfect for use in web and mobile. Support for SVG, your favourite design tool and webfont. Completely free and open source. ",
      Website: "https://coolicons.cool/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "coolors",
      Category: "Color",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Get inspired by thousands of beautiful color schemes and make something cool!\n",
      Website: "https://coolors.co/palettes/trending",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "craftwork",
      Category: "Illustration",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Discover nice objects created with Cinema 4D. Virtual reality tools and other gadgets are embodied in volumetric graphics. Customize any object in Cinema 4D to get your perfect one. All elements are fully editable. ",
      Website: "https://craftwork.design/downloads/slam/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "css.gg",
      Category: "Icons",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Pure CSS icons library, Customizable & Retina-Ready built 100% in pure CSS, SVG, SVG Sprite, styled-components, Figma and Adobe XD.",
      Website: "https://css.gg/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "cssgradient",
      Category: "Color",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "As a free css gradient generator tool, this website lets you create a colorful gradient background for your website, blog, or social media profile.",
      Website: "https://cssgradient.io/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "Culrs App",
      Category: "Color",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "We reimagined our web app into a mac app to simplify and accelerate the process of choosing colors for your design.\n\n",
      Website: "https://culrs.app/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "DaFont",
      Category: "Font",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details: "Archive of freely downloadable fonts. ",
      Website: "https://www.dafont.com/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "delesign",
      Category: "Illustration",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Use our royalty-free designs for your website, social media, blog, email newsletters, and more. View our license for more information.",
      Website: "https://delesign.com/free-designs/graphics/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "designermill",
      Category: "Freebies",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Collection of free PSDs, Sketch files, free Fonts and other resources for designers, updated every day on DesignerMill.\n",
      Website: "https://www.designermill.com/category/sketch-freebies/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "Designers.Watch",
      Category: "Learn Design",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details: "The best documentaries for designers and artists.\n",
      Website: "https://designers.watch/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "designvault",
      Category: "Inspiration",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Mobile, desktop & web UI patterns and design insiration from real products.\n",
      Website: "https://designvault.io/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "deviceshots",
      Category: "Mockups",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Easily generate device mockups with your screenshot for social media! Choose between different device categories like phones, tablets, computers and more\n",
      Website: "https://deviceshots.com/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "drawkit",
      Category: "Illustration",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details: "Beautiful, free illustrations. Updated weekly.",
      Website: "https://www.drawkit.io/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "Dribble ",
      Category: "Inspiration",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Dribbble is where designers gain inspiration, feedback, community, and jobs and is your best resource to discover and connect with designers worldwide.\n",
      Website: "dribbble.com",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "duo",
      Category: "Color",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Duo is a collection of colour combinations that I've curated from personal projects or that I've come across on the web.\n",
      Website: "https://duo.alexpate.uk/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "Eva Icons",
      Category: "Icons",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Eva Icons is a pack of 480 delightful icons available for free. Download Eva Icons to use them in your products for mobile and web apps.",
      Website: "https://akveo.github.io/eva-icons/#/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "Facebook Design — Devices ",
      Category: "Mockups",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details: "Images and Sketch files of popular devices.",
      Website: "https://facebook.design/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "Facebook Design Tools and Resources",
      Category: "Design Systems",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details: "A collection of tools and resources from Facebook Design.",
      Website: "https://facebook.design/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "feathericons",
      Category: "Icons",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Feather is a collection of simply beautiful open source icons. Each icon is designed on a 24x24 grid with an emphasis on simplicity, consistency and readability.\n",
      Website: "https://feathericons.com/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "Femke",
      Category: "Learn Design",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Hi! I'm Femke, a product designer in Toronto, Canada working in tech at Uber. On this channel i'll be sharing my learnings and experience being a designer, which will cover everything from UX Design to User Research, Prototyping and Product. I travel the world quite a bit learning about other cultures while doing research, user testing and attending creative conferences. You'll probably hear a bit about that too.\n",
      Website:
        "https://www.youtube.com/channel/UCWUGGwfTfJ0-2jUS3dZqOJA/videos",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "Figma",
      Category: "Prototyping ,Design Tools",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Build better products as a team. Design, prototype, and gather feedback all in one place with Figma.\n",
      Website: "https://www.figma.com/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "figmacrush",
      Category: "Freebies",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "FigmaCrush is a curated collection of Figma resources: UI kits, icons, website templates and all sorts of freebies created and shared by the Figma community.\n",
      Website: "https://www.figmacrush.com/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "figmafinder",
      Category: "Freebies",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Figma UI kits, resources, and freebies for designers and business owners everywhere. Speed up your projects with user-friendly resources!\n",
      Website: "https://www.figmafinder.com/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "figmafreebi",
      Category: "Freebies",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Figma Freebies is a collection of design resources for the figma community.\n",
      Website: "http://www.figmafreebi.es/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "figmafreebies",
      Category: "Freebies",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "The top community for free Figma templates, UI kits, and resources. Browse user-friendly Figma UI kits for web and mobile, then open directly in Figma.\n",
      Website: "https://www.figmafreebies.com/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "flomo Design",
      Category: "Inspiration,Mobile",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Flomo is a platform where product teams find the best user flow collection of successful products in the market. This is a really useful resource for design ...",
      Website: "https://www.flomo.design/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "Font Inspiration",
      Category: "Font",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details: "Be better at typography.\n",
      Website: "http://typ.io/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "Font Ninja",
      Category: "Font",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Access more than 3000 popular fonts\nand instantly try them in any design software.\n\n",
      Website: "https://www.fonts.ninja/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "Font Squirrel",
      Category: "Font",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Font Squirrel scours the internet for high quality, legitimately free fonts . Download thousands of completely legal, high quality, free fonts.\n",
      Website: "https://www.fontsquirrel.com/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "fontjoy",
      Category: "Font",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details: "Font pairing made simple",
      Website: "https://fontjoy.com/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "fontpair",
      Category: "Font",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Font Pair helps designers pair Google Fonts together. Beautiful Google Font combinations and pairs.\n",
      Website: "https://fontpair.co/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "fontpairings",
      Category: "Font",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details: "Check typefaces and font pairings with this interactive tool\n",
      Website: "https://fontpairings.bypeople.com/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "fontsinthewild",
      Category: "Font",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "fonts in the wild. free fonts. google fonts. adobe fonts · free google adobe. Close. Sporting Grotesque. Wl. Close. Antiqua Roman. Naba. Close. Mabry.\n",
      Website: "https://www.fontsinthewild.com/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "fontsinuse",
      Category: "Font",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details: "An independent archive of typography.\n",
      Website: "https://fontsinuse.com/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "Framer",
      Category: "Prototyping ",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "It's prototyping made simple—no code required, browser-based, and free for everyone. High-fidelity in half the time.\n\n",
      Website: "https://www.framer.com/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "Free Mockup World",
      Category: "Mockups",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Tons of free and legal, fully layered, easily customizable photo realistic PSD mockups: Ready to use in your projects, app showcases and presentations!\n",
      Website: "https://www.freemockupworld.com/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "Freebies by People",
      Category: "Freebies",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "A selection of free-for-comercial-use resources for designers and developers, conveniently collected and categorized in one place.",
      Website: "https://freebies.bypeople.com/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "freebiesbug",
      Category: "Freebies",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Freebiesbug is a web design blog showcasing free high-quality design resources like PSD files, HTML website templates, fonts and other cool stuff.\n",
      Website: "https://freebiesbug.com/figma-freebies/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "freebiesui",
      Category: "Freebies",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Are you looking for App Designs, UI Kits or Mockups? Download for free great freebies for Photoshop, Sketch, Principle & XD from FreebiesUI.\n",
      Website: "https://freebiesui.com/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "freebiesupply",
      Category: "Freebies",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "The freshest design resources for Adobe XD, Figma, Sketch, Photoshop and Adobe Illustrator.",
      Website: "https://freebiesupply.com/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "freetypography",
      Category: "Font",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "FreeTypography.com is a blog about the best free fonts, typefaces and typography for free download.\n",
      Website: "https://freetypography.com/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "fresh-folk",
      Category: "Illustration",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details: "an illustration library of\npeople and objects\n\n",
      Website: "https://fresh-folk.com/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "getloaf",
      Category: "Icons",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details: "Animated SVG icons that you'll love to use\n",
      Website: "https://getloaf.io/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "Glaze ",
      Category: "Illustration",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details: "Free illustrations, for everything",
      Website: "https://www.glazestock.com/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "glazestock",
      Category: "Illustration",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details: "Free illustrations, for everything\n\n",
      Website: "https://www.glazestock.com/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "Google Fonts",
      Category: "Font",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Making the web more beautiful, fast, and open through great typography",
      Website: "https://fonts.google.com/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "grabient",
      Category: "Color",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details: "Beautiful and simple UI for generating web gradients.",
      Website: "https://www.grabient.com/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "gradienta",
      Category: "Color",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Multicolor Gradients\nPure CSS Code, JPG Download, Open Source!\n\n",
      Website: "https://gradienta.io/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "gradihunt",
      Category: "Color",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details: "Beautiful gradient app to generate gradient color and css.",
      Website: "https://gradihunt.com/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "gratisography",
      Category: "Stock Photos",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "The world's quirkiest collection of free high-resolution pictures you can use on your personal and commercial projects",
      Website: "https://gratisography.com/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "growth.design",
      Category: "Learn Design",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Growth & UX case studies in a comic book format. Improve your product skills with real-world examples.\n\n",
      Website: "https://growth.design/case-studies",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "HANDZ",
      Category: "Illustration",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details: "A 3D illustration library",
      Website: "https://www.handz.design/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "happyhues",
      Category: "Color",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Not sure what colors to use in your designs or where to use them? Happy Hues is a color palette inspiration site that acts as a real world example as to how the colors could be used in your design projects.\n\n",
      Website: "https://www.happyhues.co/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "heroicons",
      Category: "Icons",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Beautiful hand-crafted SVG icons, by the makers of Tailwind CSS.\n\n",
      Website: "https://heroicons.com/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "hicon",
      Category: "Icons",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details: "Web Friendly Icon Pack\n",
      Website: "https://hicon.me/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "humaaans",
      Category: "Illustration",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details: "Mix-&-match illustrations of people with a design library",
      Website: "https://www.humaaans.com/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "Humane by Design",
      Category: "Learn Design",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "A resource that provides guidance for designing ethically humane digital products through patterns focused on user well-being.\n\n",
      Website: "https://humanebydesign.com/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "iconhub",
      Category: "Icons",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Save your penny and time creating from scratch, use these diverse Icon set to complete your awesome design.\n\n\n",
      Website: "https://iconhub.io/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "iconmonstr",
      Category: "Icons",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "iconmonstr uses cookies to ensure you get the best experience on the website. Learn more. OK. You will need to accept the license agreement to get this icon.\n",
      Website: "https://iconmonstr.com/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "iconpark",
      Category: "Icons",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "IconPark gives access to more than 1,400 high-quality icons, and introduces an interface for customizing your icons.",
      Website: "http://iconpark.bytedance.com/official",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "icons.mono",
      Category: "Icons",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "A simple, consistent open-source icon set designed to be used in a wide variety of digital products.\n",
      Website: "https://icons.mono.company/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "icons.vzy",
      Category: "Icons",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Beautiful SVG icons to enhance your apps and websites. Vzy icons are simple, consistent, and enjoyable to use in outline and solid styles.\n",
      Website: "https://icons.vzy.co/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "icons8",
      Category: "Icons",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Download design elements for free: icons, photos, vector illustrations, and music for your videos. All the assets made by designers → consistent quality.\n\n",
      Website: "https://icons8.com/line-awesome",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "icons8",
      Category: "Font",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details: "Fonts That People Actually Use\n",
      Website: "https://icons8.com/fonts/roboto/arial",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "iconshock",
      Category: "Icons",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "free icons and premium icon packs. Flat icons, Material icons, Glyph icons, iOS icons, Font icons, and more design styles",
      Website: "https://www.iconshock.com/svg-icons/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "iconsvg",
      Category: "Icons",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details: "Quick customizable icons for your projects",
      Website: "https://iconsvg.xyz/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "illlustrations",
      Category: "Illustration",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details: "Open source illustrations kit",
      Website: "https://illlustrations.co/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "interfacer",
      Category: "Freebies",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Interfacer is a collection of 300+ free design resources found on the Web.",
      Website: "https://interfacer.xyz/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "Invision",
      Category: "Prototyping ,Design Tools",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "InVision is the digital product design platform used to make the world's best customer experiences. InVisionApp, Inc.\n",
      Website: "https://www.invisionapp.com/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "ionicons",
      Category: "Icons",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details: "Ionicons is an open-sourced and MIT licensed icon pack.\n",
      Website: "https://ionicons.com/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "iOS Human Interface Guideline - Apple",
      Category: "Design Systems",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Find documentation and resources for designing great apps for Apple platforms.",
      Website: "https://developer.apple.com/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "iradesign",
      Category: "Illustration",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details: "Build your own amazing illustrations\n",
      Website: "https://iradesign.io/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "Is Graphics",
      Category: "Mockups",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Free and premium mockups, UI/UX tools, scene creators for busy designers.\n",
      Website: "https://www.ls.graphics/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "karthiksrinivas",
      Category: "Illustration",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details: "Charco Illustrations (Free)\n",
      Website: "https://www.karthiksrinivas.in/charco",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "khroma",
      Category: "Color",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Khroma uses AI to learn which colors you like and creates limitless palettes for you to discover, search, and save.\n",
      Website: "http://khroma.co/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "klart",
      Category: "Inspiration",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "If you're looking for kick-ass designs and copywriting, you've come to the right place. I'll share a couple of designs here every day and I hope you'll enjoy it 🍿.",
      Website: "https://klart.io/pixels",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "land-book",
      Category: "Landingpage",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Design gallery with the best and most carefully collected websites. We help creatives find inspiration & motivation to do rad stuff.",
      Website: "https://land-book.com/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "landingfolio",
      Category: "Landingpage",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Landingfolio features the best landing page inspiration, templates, resources and examples on the web. Learn from a growing library of 1982 landing page ...\n",
      Website: "https://www.landingfolio.com/?offset=2",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "lapa.ninja",
      Category: "Landingpage",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "The Best Landing Page Design Inspiration.\nLearn Design, Download Free Books & UI Kits\n",
      Website: "https://www.lapa.ninja/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "lawsofux",
      Category: "Learn Design",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Users often perceive aesthetically pleasing design as design that’s more usable.\n\n",
      Website: "https://lawsofux.com/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "learnmobile",
      Category: "Learn Design",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details: "A curated list of mobile design resources\n",
      Website: "https://learnmobile.design/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "learnux",
      Category: "Learn Design",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details: "UI Design Tools\nVideo Courses\n",
      Website: "https://learnux.io/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "librestock",
      Category: "Stock Photos",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "We scan and index the best free photos from the top stock sites, so that you can find that perfect image much, much quicker.\n",
      Website: "https://librestock.com/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "littlevisuals",
      Category: "Stock Photos",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Free, high resolution images.\nUse them anyway you want - free for commercial use.\n",
      Website: "https://littlevisuals.co/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "lookup",
      Category: "Inspiration",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Browse handpicked ui and ux design examples and find inspiration for your next website or app.\n",
      Website: "https://lookup.design/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "lottieflow",
      Category: "Icons",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Download Lottie icon animations to implement on your Webflow website.",
      Website: "https://www.lottieflow.com/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "lukaszadam",
      Category: "Illustration",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Here you’ll find MIT licensed SVG illustration images in different shapes & styles. Completely free for commercial projects - no attribution required. Open Source Illustrations.\n\n",
      Website: "https://lukaszadam.com/illustrations",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "manypixels",
      Category: "Illustration",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Each week, discover royalty-free illustrations to power up your projects.",
      Website: "https://www.manypixels.co/gallery/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "marvelapp",
      Category: "Design Systems",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "As Marvel continues to grow, both as a product and a company, one challenge we are faced with is learning how to refine the Marvel brand identity and apply it cohesively to each of our products. We created this styleguide to act as a central location where we house a live inventory of UI components, brand guidelines, brand assets, code snippets, developer guidelines and more. Anyone working on the Marvel product is encouraged to stay familiar with this styleguide and help ensure that it is kept up-to-date.",
      Website: "https://marvelapp.com/styleguide/overview/introduction",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "material",
      Category: "Icons",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Material icons are delightful, beautifully crafted symbols for common actions and items. Download on desktop to use them in your digital products for Android, iOS, and web.\n\n",
      Website: "https://material.io/resources/icons/?style=baseline",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "material",
      Category: "Color",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Create, share, and apply color palettes to your UI, as well as measure the accessibility level of any color combination",
      Website: "https://material.io/resources/color/#!/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "Material Design — Google",
      Category: "Design Systems",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details: "Material Design is an adaptable system-backed by open-source.",
      Website: "https://material.io/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "mesh-gradients",
      Category: "Color",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details: "Free Mesh\nGradient Collection\n",
      Website: "https://products.ls.graphics/mesh-gradients/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "mixkit",
      Category: "Illustration",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details: "Beautiful Art & Illustration",
      Website: "https://mixkit.co/free-stock-art/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "mobbin",
      Category: "Inspiration,Mobile",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Check out the hand-picked collection of latest mobile design patterns from apps that reflect the best in design.",
      Website: "https://mobbin.design/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "Mobbin ",
      Category: "Inspiration",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Check out the hand-picked collection of latest mobile design patterns from apps that reflect the best in design.\n",
      Website: "https://mobbin.design.com/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "mockplus",
      Category: "Freebies",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "The all-in-one product design platform for prototyping, collaboration, and creating design systems. Mockplus helps you create better design experience faster ...\n",
      Website: "https://www.mockplus.com/resource",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "mockup photos",
      Category: "Mockups",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Mockup Photos collects high quality mockup images from around the world.",
      Website: "https://mockup.photos/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "mockuphunt",
      Category: "Mockups",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "1000s of free psd mockups handpicked from trusted websites. Including popular mockup categories like stationery, business card, t-shirt, book, magazine and more\n",
      Website: "https://mockuphunt.co/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "moveast",
      Category: "Stock Photos",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "This is a journey of a Portuguese guy moving that decided that every photo should be used for free. Help yourselves and use them wherever you want (CC0)\n\n",
      Website: "https://moveast.me/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "Muzil Design Inspiration",
      Category: "Inspiration",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Designers' Secret Source: all the design inspiration you need. Served fresh.\n",
      Website: "https://muz.li/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "mycolor SPace",
      Category: "Color",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Never waste Hours on finding the perfect Color Palette again!\n",
      Website: "https://mycolor.space/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "negativespace",
      Category: "Stock Photos",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Beautiful, High-Resolution Free Stock Photos\nFor personal or commercial use, all of our CC0 licensed images are completely free to use!\n",
      Website: "https://negativespace.co/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "onepagelove",
      Category: "Landingpage",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "One Page Love is a One Page website design gallery showcasing the best Single Page websites, templates and resources.",
      Website: "https://onepagelove.com/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "Opendoodle ",
      Category: "Illustration",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "A library of sketchy illustrations of people free for personal and commercial use.\n",
      Website: "https://www.opendoodles.com/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "opendoodles",
      Category: "Illustration",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details: "A Free Set of Sketchy Illustrations\n",
      Website: "https://www.opendoodles.com/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "openpeeps",
      Category: "Illustration",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details: "A hand-drawn illustration library.\n",
      Website: "https://www.openpeeps.com/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "Origami Studio",
      Category: "Prototyping ",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "With a new canvas interface, dynamic layout, Figma & Sketch support and a ton of peformance improvements and new patches.\n",
      Website: "https://origami.design/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "Ouch by Icons8",
      Category: "Illustration",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Download Ouch vector illustrations & images in 32 different styles for free. Find illustrations in PNG, SVG from top Dribbble artists for your design projects.\n",
      Website: "https://icons8.com/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "Overflow",
      Category: "Prototyping ",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "The world's first user flow diagramming tool tailored for designers. Build and present beautiful user flow diagrams that tell a story.\n",
      Website: "https://overflow.io/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "palettte App",
      Category: "Color",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details: "The definite palette editing and remapping tool",
      Website: "https://palettte.app/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "Pexels",
      Category: "Stock Photos",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Free stock photos you can use everywhere. ✓ Free for commercial use ✓ No attribution required.\n",
      Website: "https://www.pexels.com/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "phosphoricons",
      Category: "Icons",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "A flexible icon family for interfaces, diagrams, presentations — whatever, really.",
      Website: "https://phosphoricons.com/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "picjumbo",
      Category: "Stock Photos",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details: "Beautiful FREE stock photos\n",
      Website: "https://picjumbo.com/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "picular",
      Category: "Color",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details: "The color of anything\n",
      Website: "https://picular.co/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "pixabay",
      Category: "Stock Photos",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details: "Stunning free images & royalty free stock\n",
      Website: "https://pixabay.com/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "pixeltrue",
      Category: "Illustration",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details: "170+ Free Vector\nIllustrations & Animations\n",
      Website: "https://www.pixeltrue.com/free-illustrations",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "previewed",
      Category: "Mockups",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Previewed is a mockup generator, which can help you create stunning mockups for your app.",
      Website: "https://previewed.app/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "Principle",
      Category: "Prototyping ",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Principle makes it easy to design animated and interactive user interfaces. Whether you're designing the flow of a multi-screen app, or new interactions and ...\n",
      Website: "https://principleformac.com/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "pttrns",
      Category: "Inspiration",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Pttrns is the finest collection of design patterns, resources and inspiration.\n",
      Website: "https://pttrns.com/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "remixicon",
      Category: "Icons",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Remix Icon is a set of open source neutral style system symbols elaborately crafted for designers and developers.\n",
      Website: "https://remixicon.com/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "reshot",
      Category: "Stock Photos",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details: "Authentic free stock photos\n",
      Website: "https://www.reshot.com/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "saaslandingpage",
      Category: "Inspiration,SaaS",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "SaaS Landing Page showcases the best landing page examples created by top-class SaaS companies. Get ideas and inspirations for your next design project.",
      Website: "https://saaslandingpage.com/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "saaspages",
      Category: "Inspiration,SaaS",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Screenshots, tips and tricks to build the best SaaS landing page that actually converts.",
      Website: "https://saaspages.xyz/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "saaswebsites",
      Category: "Inspiration,SaaS",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Best SaaS Websites inspiration from the best SaaS companies. Discover the best SaaS websites designs, SaaS UX designs, SaaS UI designs inpiration.",
      Website: "https://saaswebsites.com/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "screenlane",
      Category: "Inspiration",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Get inspired and keep up with the latest web & mobile app UI design trends.\n",
      Website: "https://screenlane.com/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "setproduct",
      Category: "Freebies",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Components-driven team libraries and design kits for Figma. Quickstart your every project with our smart design systems. Concentrate on the hi-end prototyping ...\n",
      Website: "https://setproduct.com/freebies",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "shapefest",
      Category: "Illustration",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details: "A massive library of free 3D shapes",
      Website: "https://www.shapefest.com/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "Shopify Polaris",
      Category: "Design Systems",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Our style guide helps us collaborate across disciplines to build a great experience for all of Shopify’s merchants.",
      Website: "https://polaris.shopify.com/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "shortcuts",
      Category: "Learn Design",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Every shortcut for designers in one place Shortcuts.design rocket emoji\n",
      Website: "https://shortcuts.design/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "shotstash",
      Category: "Stock Photos",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details: "Free Stock Photos for Creative Professionals\n",
      Website: "https://shotstash.com/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "Sketch",
      Category: "Prototyping ,Design Tools",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Sketch is a design toolkit built to help you create your best work — from your earliest ideas, through to final artwork.\n",
      Website: "https://www.sketch.com/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "sketchrepo",
      Category: "Freebies",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Sketch templates and Sketch resources for your next design project. Free, high quality icons, mockups, and UI kits for Sketch App.\n",
      Website: "https://sketchrepo.com/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "sketchvalley",
      Category: "Illustration",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Hand-drawn free vector illustration resources for your projects",
      Website: "https://sketchvalley.com/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "stubborn",
      Category: "Illustration",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Get the opportunity to design your characters using our generator absolutely for free\n",
      Website: "https://stubborn.fun/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "tablericons",
      Category: "Icons",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "800+ Customizable free SVG icons MIT licensed - Tabler Icons. Configurable stroke, color and size.\n",
      Website: "https://tablericons.com/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "teenyicons",
      Category: "Icons",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "An elegant icon set by Anja van Staden with more than a thousand icons.\n",
      Website: "https://teenyicons.com/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "templatery",
      Category: "Freebies",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "A collection of beautiful, free templates for Figma presentations.",
      Website: "https://www.templatery.co/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "The Mockup Club",
      Category: "Mockups",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "A directory of the best free design mockups for Photoshop, Sketch, Figma and InVision Studio.\n",
      Website: "https://themockup.club/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "theforgesmith",
      Category: "Icons",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details: "300+ right mix of SVG icons for your project.\n",
      Website: "https://icons.theforgesmith.com/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "theiconof",
      Category: "Icons",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Collection of 1100+ pixel perfect icons suitable for any  kind of project. All the symbols are available in most popular formats, including optimized webfont. Made with love.\n\n",
      Website: "https://www.theiconof.com/search",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "typespecimens",
      Category: "Font",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Type Specimens is a research & design project, a publication, and a community resource. \n\n",
      Website: "https://typespecimens.xyz/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "typespiration",
      Category: "Font",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Inspirational font combinations and color palettes free to use in your own designs.\n\n",
      Website: "https://typespiration.com/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "Typewolf",
      Category: "Font",
      "Top Pick": "",
      "Use Case": "Inspiration",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Typewolf helps designers choose the perfect font combination for their next design project—features web fonts in the wild, font recommendations and learning ...\n",
      Website: "https://www.typewolf.com/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "Uber Design",
      Category: "Design Systems",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "With our company’s growth and new direction, we need a brand identity that is efficient to use, flexible across applications, and able to feature localized content in a globally consistent way. These guidelines cover 9 elements: logo, color, composition, iconography, illustration, motion, photography, tone of voice, and typography.\n",
      Website: "https://brand.uber.com/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "UI Faces",
      Category: "Illustration",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "UI Faces aggregates various free avatar placeholder sources that you can use in your design mockups by copy—paste, API, plugins for Sketch, Adobe XD and more\n\n\n",
      Website: "https://uifaces.co/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "UI Sources ",
      Category: "Inspiration",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Get real design inspiration from the world's best designed apps. Analyze flows & interactions and get new insights.\n",
      Website: "https://www.uisources.com/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "uibundle",
      Category: "Freebies",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "UIBundle.com is the place where you will find the best free design resources. \n",
      Website: "https://uibundle.com/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "uijar",
      Category: "Inspiration",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details: "Handpicked design inspiration for your real life projects.\n",
      Website: "https://uijar.com/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "uispace",
      Category: "Freebies",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "High quality hand-crafted Free Sketch files, PSDs and AI freebies, free fonts, mockups, the latest free icons sets and other free vectorial resources.\n",
      Website: "https://uispace.net/free-sketch",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "uistore",
      Category: "Freebies",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Free handpicked UI Kits for your real life projects. Curated free design resources to energize your creative workflow.",
      Website: "https://www.uistore.design/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "Undraw ",
      Category: "Illustration",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "The design project with open-source illustrations for any idea you can imagine and create. Create beautiful websites, products and applications with your color, ...\n",
      Website: "https://undraw.co/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "Unsplash",
      Category: "Stock Photos",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Beautiful, free images and photos that you can download and use for any project. Better than any royalty free or stock photos.\n\n",
      Website: "https://unsplash.com/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "useanimations",
      Category: "Icons",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Animated icons in Lottie Framework and for immediate implementation to your apps or websites.\n",
      Website: "https://useanimations.com/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "usesmash",
      Category: "Illustration",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Awesome illustration constructor with colorful and trendy characters\n",
      Website: "https://usesmash.com/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "uxarchive",
      Category: "Inspiration,Mobile",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "UXArchive the world's largest library of mobile user flows. Be inspired to design the best user experiences.",
      Website: "https://uxarchive.com/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "uxmyths",
      Category: "Learn Design",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "UX Myths collects the most frequent user experience misconceptions and explains why they don't hold true. And you don't have to take our word for it, we'll show you a lot of research findings and articles by design and usability gurus.\n\n",
      Website: "https://uxmyths.com/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "vectary",
      Category: "Mockups",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Turn ideas into a 3D design with this easy-to-use online 3D modeling software. ",
      Website: "https://www.vectary.com/sketch/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "Web Gradient",
      Category: "Color",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Free for commercial or personal use by Dima Braven. WebGradients is a free collection of 180 linear gradients that you can use as content backdrops in any part ...\n",
      Website: "https://webgradients.com/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "webflow",
      Category: "Learn Design",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Explore our curated sets of lessons. Create something amazing and learn web design with Webflow — from HTML and CSS basics to SEO and CMS essentials.\n\n",
      Website: "https://university.webflow.com/courses",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "webframe",
      Category: "Inspiration",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "A showcase of beautiful and well designed web app screens for design inspiration. Including screens from behind signup/paywalls!",
      Website: "https://webframe.xyz/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "webgradients",
      Category: "Color",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "WebGradients is a free collection of 180 linear gradients that you can use as\ncontent backdrops in any part of your website. Easy copy CSS3 crossbrowser code\nand use it in a moment! We've also prepared a .PNG version of each gradient.\n As a bonus, there are packs for Sketch & Photoshop.\n\n",
      Website: "https://webgradients.com/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "webkul",
      Category: "Color",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Top-rated B2B/B2C eCommerce, marketplace, hyperlocal and mobile app development. We worked with fortune 500 in last 10 years - Let's work together.",
      Website: "https://webkul.github.io/coolhue/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "xicons",
      Category: "Icons",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "Free (do whatever you want) vector icons. Designed by Xicons.studio",
      Website: "https://xicons.co/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "zendesk",
      Category: "Design Systems",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details:
        "The source of truth for tools, standards, and best practices when building products at Zendesk.\n\n",
      Website: "https://garden.zendesk.com/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "zwicon",
      Category: "Icons",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review:
        "These icons are so clean, you aren't going to stop buying soap.  For clean, minimalist websites you can't go wrong with Zwicon.",
      Headline: "Handcrafted iconset for your next project",
      Description:
        "We created Zwicon to support our work at zwoelf as a fast and easy to use library of icons. Then we thought it would be awesome to share it with you!",
      Cost: "",
      Details:
        "The zwicon icon library was made to support our work @zwoelf. Now it is available to download.\n",
      Website: "https://www.zwicon.com/",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "NoCodeApi",
      Category: "No Code",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "Save time to Setup Server & Code for APIs",
      Description:
        "The easiest way to connect your Google Sheet, Airtable, Google Analytics, Twitter, Telegram, Open Graph API, MailChimp, 50+ application APIs without any backend.",
      Cost: "",
      Details: "Save time to Setup Server & Code for APIs\n",
      Website: "",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "Metallic Brush",
      Category: "Illustration",
      "Top Pick": "",
      "Use Case": "Tutorial",
      App: "Adobe Illustrator",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details: "",
      Website: "",
      Credit: "@creativecorner21",
      "Credit Platform": "Tik Tok",
    },
    {
      Name: "Veed.io",
      Category: "Video Editing",
      "Top Pick": "",
      "Use Case": "Tools",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details: "",
      Website: "",
      Credit: "",
      "Credit Platform": "",
    },
    {
      Name: "",
      Category: "",
      "Top Pick": "",
      "Use Case": "",
      App: "",
      Review: "",
      Headline: "",
      Description: "",
      Cost: "",
      Details: "",
      Website: "",
      Credit: "",
      "Credit Platform": "",
    },
  ];

  return null;
}

export default FavesPage;
